# Resources

Tutorials Point - Python Pandas Tutorial: <br>
https://www.tutorialspoint.com/python_pandas/index.htm

How To Filter Pandas Dataframe By Values of Column? <br>
https://cmdlinetips.com/2018/02/how-to-subset-pandas-dataframe-based-on-values-of-a-column/

Pandas Filter


Array Programming With NumPy
https://realpython.com/numpy-array-programming/

Python Data Science Handbook
https://jakevdp.github.io/PythonDataScienceHandbook/index.html

# Quick Examples

## Convert only int in a list

In [12]:
def maybe_int(s):
    try:
        return int(s)
    except (ValueError, TypeError):
        return s
    
orig_list = ['data', '18', '17', '0']
new_list = [maybe_int(v) for v in orig_list]

In [13]:
orig_list

['data', '18', '17', '0']

In [15]:
new_list

['data', 18, 17, 0]

# Numpy (arrays examples)

## from list to asarray

In [17]:
import numpy as np 

jnk_list = [[0, 0, 0, 0, 1, 0, 1, 0, 0, 0], 
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

jnk_array = np.asarray(jnk_list)

In [23]:
jnk_array.sum(axis=0)

array([0, 0, 0, 0, 1, 0, 1, 0, 0, 0])

In [25]:
jnk_array.sum(axis=1)

array([2, 0])

In [27]:
jnk_array.mean(axis=0)

array([0. , 0. , 0. , 0. , 0.5, 0. , 0.5, 0. , 0. , 0. ])

## Search a specific element in array

In [29]:
listx = np.asarray([[0,0,0],[0,0,0],[0,1,1],[0,0,0]])

In [43]:
zeros = np.where(listx[:,1] == 0)

In [44]:
listx

array([[0, 0, 0],
       [0, 0, 0],
       [0, 1, 1],
       [0, 0, 0]])

In [45]:
zeros

(array([0, 1, 3]),)

In [46]:
listx[zeros]

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## Search w/ multi conditions in array

In [47]:
traces = [['x1',11026,0,0,0,0],
          ['x0',11087,0,0,0,1],
          ['x0',11088,0,0,1,3],
          ['x0',11088,0,0,0,3],
          ['x0',11088,0,1,0,1]]

In [48]:
traces = np.array(traces)

In [50]:
traces[:,[0,1,3,5]] == ['x0', 11088, 1, 1]

array([[False, False, False, False],
       [ True, False, False,  True],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True,  True,  True]])

In [52]:
indexes = np.where(np.all(traces[:,[0,1,3,5]] == ['x0', 11088, 1, 1], axis=1))

In [53]:
indexes

(array([4]),)

In [54]:
traces[indexes]

array([['x0', '11088', '0', '1', '0', '1']], dtype='<U5')

## Search using where()

In [70]:
t = np.array([[1,2,3,'foo'],
 [2,3,4,'bar'],
 [5,6,7,'hello'],
 [8,9,1,'bar']],dtype=object) # to convert it to int

In [71]:
rows, cols = np.where(t==7)

In [72]:
rows

array([2])

In [73]:
t[rows]

array([[5, 6, 7, 'hello']], dtype=object)

# Useful Functions

In [21]:
# flatten list

import collections

def flatten(l):
    for el in l:
        if isinstance(el, collections.Iterable) and len(el) == 1:
            yield el[0]
        if isinstance(el, collections.Iterable) and not isinstance(el, (str, bytes)):
            yield from flatten(el)
        else:
            yield el

# Break

# Panda Iterations

In [7]:
import pandas as pd

In [1]:
mem_data = [{'name': "a dancing mem",
             'Activity': ["dancing", "practicing"],
             'Mood': "happy",
             'Person': "Tarah",
             'Place': "spotlight studio",
             'Thing': "shoes",
             'Time': "night"},
            {'name': "a studying mem",
             'Activity': ["studying", "working", "talking"],
             'Mood': "sad",
             'Person': "Joud",
             'Place': "Davis",
             'Thing': "books",
             'Time': "noon"},
            {'name': "a running mem",
             'Activity': ["running"],
             'Mood': "excited",
             'Person': "me",
             'Place': "trail",
             'Thing': "basketball",
             'Time': "night"},
           ]

In [9]:
df = pd.DataFrame(mem_data) 

In [12]:
df

Activity     Mood Person             Place       Thing  \
0         [dancing, practicing]    happy  Tarah  spotlight studio       shoes   
1  [studying, working, talking]      sad   Joud             Davis       books   
2                     [running]  excited     me             trail  basketball   

    Time            name  
0  night   a dancing mem  
1   noon  a studying mem  
2  night   a running mem

In [15]:
# print rows

for index, row in df.iterrows():
    print(row['name'])
    

a dancing mem
a studying mem
a running mem


In [16]:
# iterate through each row in "name" and print the list of activites

for alist, name in zip(df.Activity, df.name):
    for item in alist:
        print(name, ':', item)

a dancing mem : dancing
a dancing mem : practicing
a studying mem : studying
a studying mem : working
a studying mem : talking
a running mem : running


In [19]:
# bad iterations lol 

for i,row in df.iterrows():
    for activity_row in df.Activity:
        print(activity_row, row["name"])
        
print("\n")

for activity_row in df.Activity:
    for name in df.name:
        for item in activity_row:
            print(name, "+", item)

['dancing', 'practicing'] a dancing mem
['studying', 'working', 'talking'] a dancing mem
['running'] a dancing mem
['dancing', 'practicing'] a studying mem
['studying', 'working', 'talking'] a studying mem
['running'] a studying mem
['dancing', 'practicing'] a running mem
['studying', 'working', 'talking'] a running mem
['running'] a running mem


a dancing mem + dancing
a dancing mem + practicing
a studying mem + dancing
a studying mem + practicing
a running mem + dancing
a running mem + practicing
a dancing mem + studying
a dancing mem + working
a dancing mem + talking
a studying mem + studying
a studying mem + working
a studying mem + talking
a running mem + studying
a running mem + working
a running mem + talking
a dancing mem + running
a studying mem + running
a running mem + running


In [25]:
# idk what but oh well 

activities_list = df.Activity.to_list()
activities_list = list(flatten(activities_list))

name_list = df.name.to_list()

for activity,mem_name in zip(activities_list, name_list):
    print(activity,mem_name)

dancing a dancing mem
practicing a studying mem
studying a running mem


In [28]:
# doesn't work 

l = df.Activity.to_list()

flat_list = [item for sublist in l for item in sublist]

flatten = lambda l: [item for sublist in l for item in sublist]

flat_list = []
for sublist in l:
    for item in sublist:
        flat_list.append(item)
        
flat_list

['dancing', 'practicing', 'studying', 'working', 'talking', 'running']